Repository C-KLex/Phraends, pull requests merged in 2023-07, with the labels that each got.

#3 Frontend first PR
  Phraends_Flask/.DS_Store
  Phraends_Flask/Backend/Crawler/Crawler.py
  Phraends_Flask/Backend/Crawler/__init__.py
  Phraends_Flask/Backend/Model_API/ModelAPI.py
  Phraends_Flask/Backend/Model_API/__init__.py
  Phraends_Flask/Backend/__init__.py
  Phraends_Flask/__init__.py
  Phraends_Flask/static/style.css
  Phraends_Flask/templates/home.html
  Phraends_Flask/templates/phrase.html
Labels: documentation

#4 Building Frontend Application with Streamlit
  __main__.py
Labels: enhancement

#2 ModelApiProcessing first PR
  Phreands_Flask/Backend/Model_API/ModelAPI.py
Labels: enhancement

#1 Web crawling first PR
  Phraends_Flask/Backend/Crawler/Crawler.py
  Phreands_Flask/Backend/Crawler/Crawler.py
Labels: documentation

#7 Frontend 2nd PR: Confirm Use of Streamlit and Delete Flask Files
  Phraends_Flask/__init__.py
  Phraends_Flask/templates/home.html
  Phraends_Flask/templates/phrase.html
Labels: refactory

#12 Web crawling 4th PR
  Phraends_Flask/Backend/Crawler/Crawler.py
  Phraends_Flask/Backend/Crawler/the_news_texts.txt
Labels: enhancement
